#

UTILSRCS += misc.c stack.c 
UTILSRCS += ElementaryClasses.c
UTILSRCS += box_vector.c int_vector.c rule_vector.c ll_vector.c u_multiset.c
UTILSRCS += IntervalUtilities.c
UTILSRCS += rule_reader.c

LDFLAGS+= -lpcap
