/*
 * Copyright 2014-2016 Nippon Telegraph and Telephone Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_defines.conf 7011 2002-05-08 05:42:47Z hardaker $
 */
#ifndef DOT1DBASEPORTTABLE_COLUMNS_H
#define DOT1DBASEPORTTABLE_COLUMNS_H

/* column number definitions for table dot1dBasePortTable */
#define COLUMN_DOT1DBASEPORT		1
#define COLUMN_DOT1DBASEPORTIFINDEX		2
#define COLUMN_DOT1DBASEPORTCIRCUIT		3
#define COLUMN_DOT1DBASEPORTDELAYEXCEEDEDDISCARDS		4
#define COLUMN_DOT1DBASEPORTMTUEXCEEDEDDISCARDS		5
#endif /* DOT1DBASEPORTTABLE_COLUMNS_H */
