/*
 * Copyright 2014-2016 Nippon Telegraph and Telephone Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.access_functions.conf 11358 2004-10-14 12:57:34Z dts12 $
 */
#ifndef DOT1DBASEPORTTABLE_ACCESS_H
#define DOT1DBASEPORTTABLE_ACCESS_H

/** User-defined data access functions for data in table dot1dBasePortTable */
/** row level accessors */
Netsnmp_First_Data_Point  dot1dBasePortTable_get_first_data_point;
Netsnmp_Next_Data_Point   dot1dBasePortTable_get_next_data_point;
void *dot1dBasePortTable_create_data_context(netsnmp_variable_list *index_data,
    int column);

void dot1dBasePortTable_data_free(void *data_context,
                                  netsnmp_iterator_info *mydata);
void dot1dBasePortTable_loop_free(void *data_context,
                                  netsnmp_iterator_info *mydata);


/** column accessors */
int32_t *get_dot1dBasePort(void *data_context, size_t *ret_len);
int32_t *get_dot1dBasePortIfIndex(void *data_context, size_t *ret_len);
oid *get_dot1dBasePortCircuit(void *data_context, size_t *ret_len);
uint32_t *get_dot1dBasePortDelayExceededDiscards(void *data_context,
    size_t *ret_len);
uint32_t *get_dot1dBasePortMtuExceededDiscards(void *data_context,
    size_t *ret_len);

#endif /* DOT1DBASEPORTTABLE_ACCESS_H */
