/*
 * Copyright 2014-2016 Nippon Telegraph and Telephone Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */

#include <stdint.h>
#include <stdbool.h>

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "dot1dBaseType.h"
#include "dataplane_interface.h"

/** Initializes the dot1dBaseType module */
void
init_dot1dBaseType(void) {
  static oid dot1dBaseType_oid[] = { 1,3,6,1,2,1,17,1,3 };

  DEBUGMSGTL(("dot1dBaseType", "Initializing\n"));

  netsnmp_register_scalar(
    netsnmp_create_handler_registration("dot1dBaseType", handle_dot1dBaseType,
                                        dot1dBaseType_oid, OID_LENGTH(dot1dBaseType_oid),
                                        HANDLER_CAN_RONLY
                                       ));
}

int
handle_dot1dBaseType(netsnmp_mib_handler *handler,
                     netsnmp_handler_registration *reginfo,
                     netsnmp_agent_request_info   *reqinfo,
                     netsnmp_request_info         *requests) {
  int32_t bridge_type;
  (void) handler;
  (void) reginfo;

  switch (reqinfo->mode) {

    case MODE_GET:
      if (dataplane_bridge_stat_get_type(&bridge_type) == LAGOPUS_RESULT_OK) {
        snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                 (u_char *) &bridge_type,
                                 sizeof(bridge_type));
        break;
      }

    default:
      /* we should never get here, so this is a really bad error */
      snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dBaseType\n",
               reqinfo->mode );
      return SNMP_ERR_GENERR;
  }

  return SNMP_ERR_NOERROR;
}
