/*
 * Copyright 2014-2016 Nippon Telegraph and Telephone Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */

#include <stdint.h>
#include <stdbool.h>

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

#include "dot1dBaseBridgeAddress.h"
#include "dataplane_interface.h"

/** Initializes the dot1dBaseBridgeAddress module */
void
init_dot1dBaseBridgeAddress(void) {
  static oid dot1dBaseBridgeAddress_oid[] = { 1,3,6,1,2,1,17,1,1 };

  DEBUGMSGTL(("dot1dBaseBridgeAddress", "Initializing\n"));

  netsnmp_register_scalar(
    netsnmp_create_handler_registration("dot1dBaseBridgeAddress",
                                        handle_dot1dBaseBridgeAddress,
                                        dot1dBaseBridgeAddress_oid, OID_LENGTH(dot1dBaseBridgeAddress_oid),
                                        HANDLER_CAN_RONLY
                                       ));
}

int
handle_dot1dBaseBridgeAddress(netsnmp_mib_handler *handler,
                              netsnmp_handler_registration *reginfo,
                              netsnmp_agent_request_info   *reqinfo,
                              netsnmp_request_info         *requests) {
  uint8_t *hw_address = NULL;
  size_t length;

  (void) handler;
  (void) reginfo;

  switch (reqinfo->mode) {

    case MODE_GET:
      if (dataplane_bridge_stat_get_address(hw_address,
                                            &length) == LAGOPUS_RESULT_OK) {
        snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                 (u_char *) hw_address,
                                 length);
        free(hw_address);
        break;
      } else {
        snmp_log(LOG_ERR, "failed to get the bridge address\n");
      }

    default:
      /* we should never get here, so this is a really bad error */
      snmp_log(LOG_ERR, "unknown mode (%d) in handle_dot1dBaseBridgeAddress\n",
               reqinfo->mode );
      return SNMP_ERR_GENERR;
  }

  return SNMP_ERR_NOERROR;
}
