/*
 * Copyright 2014-2016 Nippon Telegraph and Telephone Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: this file originally auto-generated by mib2c using
 *  : mib2c.column_defines.conf 7011 2002-05-08 05:42:47Z hardaker $
 */
#ifndef IFTABLE_COLUMNS_H
#define IFTABLE_COLUMNS_H

/* column number definitions for table ifTable */
#define COLUMN_IFINDEX		1
#define COLUMN_IFDESCR		2
#define COLUMN_IFTYPE		3
#define COLUMN_IFMTU		4
#define COLUMN_IFSPEED		5
#define COLUMN_IFPHYSADDRESS		6
#define COLUMN_IFADMINSTATUS		7
#define COLUMN_IFOPERSTATUS		8
#define COLUMN_IFLASTCHANGE		9
#define COLUMN_IFINOCTETS		10
#define COLUMN_IFINUCASTPKTS		11
#define COLUMN_IFINNUCASTPKTS		12
#define COLUMN_IFINDISCARDS		13
#define COLUMN_IFINERRORS		14
#define COLUMN_IFINUNKNOWNPROTOS		15
#define COLUMN_IFOUTOCTETS		16
#define COLUMN_IFOUTUCASTPKTS		17
#define COLUMN_IFOUTNUCASTPKTS		18
#define COLUMN_IFOUTDISCARDS		19
#define COLUMN_IFOUTERRORS		20
#define COLUMN_IFOUTQLEN		21
#define COLUMN_IFSPECIFIC		22
#endif /* IFTABLE_COLUMNS_H */
