/*
 * Copyright 2014-2016 Nippon Telegraph and Telephone Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate_access.conf 17483 2009-04-09 08:54:46Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "ifTable.h"
#include "ifTable_access.h"

inline static void
ifTable_setup_valid_colmuns(netsnmp_table_registration_info *table_info) {
  static unsigned int my_columns[] = {
    COLUMN_IFINDEX,
    COLUMN_IFDESCR,
    COLUMN_IFTYPE,
    COLUMN_IFMTU,
    COLUMN_IFSPEED,
    COLUMN_IFPHYSADDRESS,
    COLUMN_IFADMINSTATUS,
    COLUMN_IFOPERSTATUS,
    COLUMN_IFLASTCHANGE,
    COLUMN_IFINOCTETS,
    COLUMN_IFINUCASTPKTS,
    /* COLUMN_IFINNUCASTPKTS, */ /* DEPRECATED */
    COLUMN_IFINDISCARDS,
    COLUMN_IFINERRORS,
    /* COLUMN_IFINUNKNOWNPROTOS, */ /* not supported */
    COLUMN_IFOUTOCTETS,
    COLUMN_IFOUTUCASTPKTS,
    /* COLUMN_IFOUTNUCASTPKTS, */ /* DEPRECATED */
    COLUMN_IFOUTDISCARDS,
    COLUMN_IFOUTERRORS
    /* COLUMN_IFOUTQLEN, */ /* DEPRECATED */
    /* COLUMN_IFSPECIFIC, */ /*DEPRECATED */
  };
  static netsnmp_column_info valid_columns;
  valid_columns.isRange = 0;
  valid_columns.details.list = my_columns;
  valid_columns.list_count = sizeof(my_columns)/sizeof(my_columns[0]);
  table_info->valid_columns = &valid_columns;
}

/** Initialize the ifTable table by defining
    its contents and how it's structured */
void
initialize_table_ifTable(void) {
  static oid ifTable_oid[] = {1,3,6,1,2,1,2,2};
  netsnmp_table_registration_info *table_info;
  netsnmp_handler_registration *my_handler;
  netsnmp_iterator_info *iinfo;

  /** create the table registration information structures */
  table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
  iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);

  my_handler = netsnmp_create_handler_registration("ifTable",
               ifTable_handler,
               ifTable_oid,
               OID_LENGTH(ifTable_oid),
               HANDLER_CAN_RONLY
                                                  );

  if (!my_handler || !table_info || !iinfo) {
    snmp_log(LOG_ERR, "malloc failed in initialize_table_ifTable\n");
    SNMP_FREE(my_handler);
    SNMP_FREE(table_info);
    SNMP_FREE(iinfo);
    return; /** Serious error. */
  }

  /***************************************************
   * Setting up the table's definition
   */
  netsnmp_table_helper_add_indexes(table_info,
                                   ASN_INTEGER, /** index: ifIndex */
                                   0);

  /** Define the minimum and maximum accessible columns.  This
      optimizes retrival. */
  table_info->min_column = 1;
  table_info->max_column = 22;

  ifTable_setup_valid_colmuns(table_info);

  /** iterator access routines */
  iinfo->get_first_data_point = ifTable_get_first_data_point;
  iinfo->get_next_data_point = ifTable_get_next_data_point;

  /* not use iinfo->make_data_context = ifTable_context_convert_function; */
  iinfo->free_data_context = ifTable_data_free;

  /* not use iinfo->free_loop_context = ifTable_loop_free; */
  iinfo->free_loop_context_at_end = ifTable_loop_free;

  /** tie the two structures together */
  iinfo->table_reginfo = table_info;

  /***************************************************
   * registering the table with the master agent
   */
  DEBUGMSGTL(("initialize_table_ifTable",
              "Registering table ifTable as a table iterator\n"));
  netsnmp_register_table_iterator(my_handler, iinfo);
}

/** Initializes the ifTable module */
void
init_ifTable(void) {
  /** here we initialize all the tables we're planning on supporting */
  initialize_table_ifTable();
}

/** handles requests for the ifTable table, if anything else needs to be done */
int
ifTable_handler(
  netsnmp_mib_handler               *handler,
  netsnmp_handler_registration      *reginfo,
  netsnmp_agent_request_info        *reqinfo,
  netsnmp_request_info              *requests) {

  netsnmp_request_info *request;
  netsnmp_table_request_info *table_info;
  netsnmp_variable_list *var;

  void *data_context = NULL;

  (void)handler;
  (void)reginfo;

  if (reqinfo == NULL) {
    return SNMP_ERR_GENERR;
  }

  for (request = requests; request; request = request->next) {
    var = request->requestvb;
    if (request->processed != 0) {
      continue;
    }

    switch (reqinfo->mode) {
      case MODE_GET:
        data_context =  netsnmp_extract_iterator_context(request);
        if (data_context == NULL) {
          netsnmp_set_request_error(reqinfo, request,
                                    SNMP_NOSUCHINSTANCE);
          continue;
        }
        break;
      default:
        break;
    }

    /** extracts the information about the table from the request */
    table_info = netsnmp_extract_table_info(request);
    /** table_info->colnum contains the column number requested */
    /** table_info->indexes contains a linked list of snmp variable
        bindings for the indexes of the table.  Values in the list
        have been set corresponding to the indexes of the
        request */
    if (table_info == NULL) {
      continue;
    }

    switch (reqinfo->mode) {
      case MODE_GET:
        switch (table_info->colnum) {
          case COLUMN_IFINDEX: {
            int32_t *retval;
            size_t retval_len = 0;
            retval = get_ifIndex(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_INTEGER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFDESCR: {
            char *retval;
            size_t retval_len = 0;
            retval = get_ifDescr(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFTYPE: {
            int32_t *retval;
            size_t retval_len = 0;
            retval = get_ifType(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_INTEGER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFMTU: {
            int32_t *retval;
            size_t retval_len = 0;
            retval = get_ifMtu(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_INTEGER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFSPEED: {
            uint32_t *retval;
            size_t retval_len = 0;
            retval = get_ifSpeed(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_GAUGE,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFPHYSADDRESS: {
            char *retval;
            size_t retval_len = 0;
            retval = get_ifPhysAddress(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFADMINSTATUS: {
            int32_t *retval;
            size_t retval_len = 0;
            retval = get_ifAdminStatus(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_INTEGER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFOPERSTATUS: {
            int32_t *retval;
            size_t retval_len = 0;
            retval = get_ifOperStatus(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_INTEGER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFLASTCHANGE: {
            uint32_t *retval;
            size_t retval_len = 0;
            retval = get_ifLastChange(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_TIMETICKS,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFINOCTETS: {
            uint32_t *retval;
            size_t retval_len = 0;
            retval = get_ifInOctets(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_COUNTER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFINUCASTPKTS: {
            uint32_t *retval;
            size_t retval_len = 0;
            retval = get_ifInUcastPkts(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_COUNTER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFINNUCASTPKTS: {
            uint32_t *retval;
            size_t retval_len = 0;
            retval = get_ifInNUcastPkts(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_COUNTER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFINDISCARDS: {
            uint32_t *retval;
            size_t retval_len = 0;
            retval = get_ifInDiscards(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_COUNTER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFINERRORS: {
            uint32_t *retval;
            size_t retval_len = 0;
            retval = get_ifInErrors(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_COUNTER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFINUNKNOWNPROTOS: {
            uint32_t *retval;
            size_t retval_len = 0;
            retval = get_ifInUnknownProtos(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_COUNTER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFOUTOCTETS: {
            uint32_t *retval;
            size_t retval_len = 0;
            retval = get_ifOutOctets(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_COUNTER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFOUTUCASTPKTS: {
            uint32_t *retval;
            size_t retval_len = 0;
            retval = get_ifOutUcastPkts(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_COUNTER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFOUTNUCASTPKTS: {
            uint32_t *retval;
            size_t retval_len = 0;
            retval = get_ifOutNUcastPkts(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_COUNTER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFOUTDISCARDS: {
            uint32_t *retval;
            size_t retval_len = 0;
            retval = get_ifOutDiscards(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_COUNTER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFOUTERRORS: {
            uint32_t *retval;
            size_t retval_len = 0;
            retval = get_ifOutErrors(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_COUNTER,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFOUTQLEN: {
            uint32_t *retval;
            size_t retval_len = 0;
            retval = get_ifOutQLen(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_GAUGE,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          case COLUMN_IFSPECIFIC: {
            oid *retval;
            size_t retval_len = 0;
            retval = get_ifSpecific(data_context, &retval_len);
            if (retval)
              snmp_set_var_typed_value(var, ASN_OBJECT_ID,
                                       (const u_char *) retval,
                                       retval_len);
          }
          break;

          default:
            /** We shouldn't get here */
            snmp_log(LOG_ERR, "problem encountered in ifTable_handler: unknown column\n");
        }
        break;
      default:
        snmp_log(LOG_ERR,
                 "problem encountered in ifTable_handler: unsupported mode\n");
    }
  }
  return SNMP_ERR_NOERROR;
}
