/*
 * Copyright 2014-2016 Nippon Telegraph and Telephone Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef __SNMP_COMMON_H__
#define __SNMP_COMMON_H__

#include <sys/types.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <netinet/in.h>
#include <net/if.h>
#include <net/if_arp.h>

#include "lagopus_apis.h"

// expected only MAC address
#define PHYSADDRESS_MAXLEN 6

/* Typical data structure for a row entry
   (auto generated by the 'iterate' template)*/
struct ifTable_entry {
  /* Index values */
  int32_t ifIndex;
  /* Column values */
  char ifDescr[IFNAMSIZ + 1];
  size_t ifDescr_len;
  int32_t ifType;
  int32_t ifMtu;
  uint32_t ifSpeed;
  char ifPhysAddress[PHYSADDRESS_MAXLEN];
  size_t ifPhysAddress_len;
  int32_t ifAdminStatus;
  int32_t old_ifAdminStatus;
  int32_t ifOperStatus;
  uint32_t ifLastChange;
  uint32_t ifInOctets;
  uint32_t ifInUcastPkts;
  uint32_t ifInNUcastPkts;
  uint32_t ifInDiscards;
  uint32_t ifInErrors;
  uint32_t ifInUnknownProtos;
  uint32_t ifOutOctets;
  uint32_t ifOutUcastPkts;
  uint32_t ifOutNUcastPkts;
  uint32_t ifOutDiscards;
  uint32_t ifOutErrors;
  uint32_t ifOutQLen;

  /* for Bridge MIB */

  int32_t dot1dBasePortIfIndex;
  /* TODO set a valid value if needed */
  /* oid dot1dBasePortCircuit[10]; */
  /* size_t dot1dBasePortCircuit_len; */
  uint32_t dot1dBasePortDelayExceededDiscards;
  uint32_t dot1dBasePortMtuExceededDiscards;
};

#endif /* ! __SNMP_COMMON_H__ */
