/*
 * Copyright 2014-2016 Nippon Telegraph and Telephone Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate_access.conf 17483 2009-04-09 08:54:46Z dts12 $
 */
#ifndef IFTABLE_H
#define IFTABLE_H

/** other required module components */
config_require(ifTable_access)
config_require(ifTable_checkfns)

/* function declarations */
void init_ifTable(void);
void initialize_table_ifTable(void);
Netsnmp_Node_Handler ifTable_handler;


/* column number definitions for table ifTable */
#include "ifTable_columns.h"

/* enum definions */
#include "ifTable_enums.h"

#endif /** IFTABLE_H */
