/*
 * Copyright 2014-2016 Nippon Telegraph and Telephone Corporation.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.notify.conf 10110 2004-04-15 12:29:19Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "warmStart.h"

static oid snmptrap_oid[] = {1, 3, 6, 1, 6, 3, 1, 1, 4, 1, 0};

int
send_warmStart_trap( void ) {
  netsnmp_variable_list  *var_list = NULL;
  oid warmStart_oid[] = { 1,3,6,1,6,3,1,1,5,2 };

  /*
   * Set the snmpTrapOid.0 value
   */
  snmp_varlist_add_variable(&var_list,
                            snmptrap_oid, OID_LENGTH(snmptrap_oid),
                            ASN_OBJECT_ID,
                            (const u_char *)warmStart_oid, sizeof(warmStart_oid));
  /*
   * Add any extra (optional) objects here
   */

  /*
   * Send the trap to the list of configured destinations
   *  and clean up
   */
  send_v2trap( var_list );
  snmp_free_varbind( var_list );

  return SNMP_ERR_NOERROR;
}
