#!/bin/sh

# Consider to use -p ?
#	It makes (char *)&((*aptr)->a) to (char *) & ((*aptr)->a), though.

beautify() {
    astyle \
	--mode=c \
	--style=java \
	-xC79 -s2 -m0 \
	-L -S -H \
	-xL -w -j \
	-o -O \
	-k3 \
	-z2 \
	-r \
	-n \
	${1+"$@"}
}


beautify ${1+"$@"}
exit 0


